#Per-profile cosmetica settings
#Sat Jul 04 15:19:44 EEST 2026
=\=\=\=\=\=\=
<<<<<<<=HEAD
>>>>>>>=11567afa174458da9abab21869157d2e0a88f1d9
enable_version_checker=true
show_own_nametag=true
toggle_outfit_wheel=false
use_cloud_settings=false
