#Per-profile cosmetica settings
#Tue Jul 14 21:22:52 CEST 2026
=\=\=\=\=\=\=
<<<<<<<=HEAD
>>>>>>>=11567afa174458da9abab21869157d2e0a88f1d9
enable_version_checker=true
show_own_nametag=true
toggle_outfit_wheel=false
use_cloud_settings=false
