#Per-profile cosmetica settings
<<<<<<< HEAD
#Fri Jul 03 18:58:04 EEST 2026
=======
#Fri Jul 03 17:13:08 CEST 2026
>>>>>>> 11567afa174458da9abab21869157d2e0a88f1d9
enable_version_checker=true
show_own_nametag=true
toggle_outfit_wheel=false
use_cloud_settings=false
