ServerEvents.recipes(event => {
  event.remove({id:"dndesires:handheld_saw"})
  event.remove({id:"dndesires:handheld_drill"})
  event.remove({id:"dndesires:gatling_breaker"})
  event.remove({id:"dndesires:haunting_sail"})
  event.remove({id:"dndesires:splashing_sail"})
  event.remove({id:"dndesires:smoking_sail"})
  event.remove({id:"dndesires:blasting_sail"})
  event.remove({id:"dndesires:seething_sail"})
  event.remove({id:"dndesires:freezing_sail"})
  event.remove({id:"dndesires:sanding_sail"})
  event.remove({id:"dndesires:dragon_breathing_sail"})
  event.remove({id:"create_connected:item_application/seething_catalyst_from_empty"})
})

