ServerEvents.recipes(event => {
  event.remove({id:"dndesires:handheld_saw"})
  event.remove({id:"dndesires:handheld_drill"})
  event.remove({id:"dndesires:gatling_breaker"})
  event.remove({id:"dndesires:crafting/fan_catalyst/blasting_sail"})
  event.remove({id:"dndesires:crafting/fan_catalyst/dragon_breathing_sail"})
  event.remove({id:"dndesires:crafting/fan_catalyst/freezing_sail"})
  event.remove({id:"dndesires:crafting/fan_catalyst/haunting_sail"})
  event.remove({id:"dndesires:crafting/fan_catalyst/sanding_sail"})
  event.remove({id:"dndesires:crafting/fan_catalyst/seething_sail"})
  event.remove({id:"dndesires:crafting/fan_catalyst/smoking_sail"})
  event.remove({id:"dndesires:crafting/fan_catalyst/splashing_sail"})
  event.remove({id:"create_connected:item_application/seething_catalyst_from_empty"})
})

