	["Armor Effects".eclipse_soldier]
		effects = []

	["Armor Effects".dragonslayer]
		effects = []

	["Armor Effects".hero]
		effects = []

	["Armor Effects".golden_horns]
		effects = []

	["Armor Effects".thief]
		effects = []

	["Armor Effects".wandering_wizard]
		effects = []

	["Armor Effects".chess_board_knight]
		effects = []

	["Armor Effects".dark_lord]
		effects = []

	["Armor Effects".sunset_wings]
		effects = []

	["Armor Effects".fog_guard]
		effects = []

	["Armor Effects".dark_cover]
		effects = []

	["Armor Effects".spark_of_dawn]
		effects = []

	["Armor Effects".golden_execution]
		effects = []

	["Armor Effects".forgotten_trace]
		effects = []

	["Armor Effects".redeemer]
		effects = []

	["Armor Effects".twinned]
		effects = []

	["Armor Effects".gilded_hunt]
		effects = []

	["Armor Effects".lady_maria]
		effects = []

	["Armor Effects".crucible_knight]
		effects = []

	["Armor Effects".evening_ghost]
		effects = []

	["Armor Effects".ronin]
		effects = []

	["Armor Effects".malenia]
		effects = []

	["Armor Effects".old_knight]
		effects = []

	["Armor Effects".silver_knight]
		effects = []

	["Armor Effects".dead_gladiator]
		effects = []

	["Armor Effects".flesh_of_the_feaster]
		effects = []

	["Armor Effects".wind_worshipper]
		effects = []

	["Armor Effects".grave_sentinel]
		effects = []

	["Armor Effects".ornstein]
		effects = []
